export const LIST_USER_STORIES  = 'LISTUSER_STORIES';
export const ADD_USER_STORY  = 'ADD_USER_STORY';
export const DETAILS_USER_STORY  = 'DETAILS_USER_STORY';
export const UPDATE_USER_STORY  = 'UPDATE_USER_STORY';
export const DELETE_USER_STORY  = 'DELETE_USER_STORY';
